#ifndef CUSTOM_PYTHON_TYPE_H_INCLUDED
#define CUSTOM_PYTHON_TYPE_H_INCLUDED

#define PY_SSIZE_T_CLEAN
#include <Python.h>

PyMODINIT_FUNC PyInit_custom(void);

#endif // CUSTOM_PYTHON_TYPE_HPP_INCLUDED